import Head from 'next/head';
import Post from './components/Post';
import fs from 'fs';
import path from 'path';
import matter from 'gray-matter';

export default function Home({ posts }) {
  return (
    <div>
      <Head>
        <title>Static Blog With Next.js and Markdown</title>
        <meta name='description' content='Generated by Next.js' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className='posts'>
        {posts.map((post, index) => (
          <Post post={post} />
        ))}
      </div>
    </div>
  );
}

export async function getStaticProps() {
  // Get files from the posts directory
  const files = fs.readdirSync(path.join('posts'));

  //Get slug and frontmatter from posts
  const posts = files.map((filename) => {
    //create slug
    const slug = filename.replace('.md', '');
    //create front matter
    const markdownWithMeta = fs.readFileSync(
      path.join('posts', filename),
      'utf-8'
    );
    const { data: frontmatter } = matter(markdownWithMeta);

    return {
      slug,
      frontmatter,
    };
  });

  // console.log(posts);

  return {
    props: {
      posts,
    },
  };
}
